### ISSUE TITLE
{A,B,X,Y}_was_released does not always work

### ISSUE THREAD

**Issue by rickwierenga** [sdickreuter/python-gamepad#1]
In `_read_gamepad`, `_old_state` is only updated if a new state was read. This means that if you don't change touch anything after releasing one of A,B,X,Y, `_old_state` will not be changed, and `{A,B,X,Y}_was_released` will keep returning True, potentially long after it was released.

**Comment by rickwierenga** [comment]
Fixed in my fork https://github.com/rickwierenga/python-gamepad. Will create a PR soon. I'll probably be making more changes over the weekend.

**Comment by sdickreuter** [comment]
Hi Rick,

would you mind taking over the repo? It's been years since I used the code and I don't even own the gamepad anymore. If you agree I would just put a link to your fork in the readme and archive the repo.

**Comment by rickwierenga** [comment]
Sure

**Comment by sdickreuter** [comment]
Cool, thanks for taking over!
